### ISSUE TITLE
Android Basics issue: Optional step says decrease sides, should say increase instead

### ISSUE THREAD

**Issue by EDLLT** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#129]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-unit-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-unit-tests#2

**In which task and step of the codelab can this issue be found?**
Task 3, The optional Step 8

**Describe the problem**
_"8. Optional: For extra practice, modify the dice to be 4- or 5-sided without changing the assertion to see the test fail."_

Step 8 says that the dice should be modified to be 4 or 5 sided in order to make the test fail.
However, the assertTrue only checks whether a value is between 1 and 6 as seen below
`assertTrue("The value of rollResult was not between 1 and 6", rollResult in 1..6)`

The optional step should instead tell us to increase the number of sides in the dice for the test to fail

**Comment by karlgg** [comment]
Even if increasing the sides, it will only fail on the random chance it picks something bigger than 6. You might choose a thousand sides and there's still the possibility of rolling a six or less.

And changing the _assertion_ to be a range of 4 or 5 would have the same result, it _might not_ always fail. I set the assertion to 1..4 (with sides still at 6) and it took four tests before it found a failure.

**Comment by EDLLT** [comment]
> Even if increasing the sides, it will only fail on the random chance it picks something bigger than 6. You might choose a thousand sides and there's still the possibility of rolling a six or less.
> 
> And changing the _assertion_ to be a range of 4 or 5 would have the same result, it _might not_ always fail. I set the assertion to 1..4 (with sides still at 6) and it took four tests before it found a failure.

Oh I see, so it tracks whether if all possibilities had been exhausted before determining whether or not the assertion failed.
Thanks
