### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by doraba** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#14]
URL: https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#1

Step #2 Add an image to your project

The image should be downloaded as androidparty.png but below, inside the drawable folder, is listed as androidparty.jpg

**Comment by ashnohe** [comment]
triage notes:
Image of step 11 should change to show .png instead of .jpg.
