### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by doraba** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#15]
URL https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#3

Android Studio version: 4.2

Task #4. Adopt good coding practices 

Translating, Step 2

There isn't a Fix button available. The user can open the Extract Resource dialog by switching to Split or Code mode, hover over the hardcoded text, and then select "Extract string resource".

**Comment by ashnohe** [comment]
Thank you @doraba for reaching out.
Cannot replicate with latest version of Android Studio, Arctic Fox. Closing for now as cannot replicate. Let us know if you still encounter this issue. Thanks!
