### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by cackazar** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#156]
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#1

Steps 8 and 9.

I have been following several of the tutorials about developing app with android studio and for the most part all of the steps and images match exactly with what is shown in the tutorial except for when adding a drawable. When the tutorial shows the action of adding the image it simply shows that you can click import and android studio imports the image and it shows up in the Drawable list and it can now be used as a resource. However, when I try to add the image an extra window pops up with 2 (two) extra options that are "qualifier" and "value." I personally do not understand what these values do and it seems selecting the wrong ones may have also led to a separate issue later on. After I move the image to the background the warnings indicating that the TextViews are hardcoded disappear.

**Versions**
_Android Studio version:_ 
Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 29, 2022
Runtime version: 11.0.13+0-b1751.21-8125866 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

![Before image is moved to the background](https://user-images.githubusercontent.com/99628676/204105844-ff746e0b-cbc9-4c23-9db8-03a35b799d03.png)
![After image is moved to the background](https://user-images.githubusercontent.com/99628676/204105847-58837b0d-65dd-4867-b4b2-fe3f95bb43f5.png)

**Comment by rapid-killer-9** [comment]
@cackazar 
from where u have downloaded the image ?
can u give me the link of it  

i am not able to download it 
it seems image is not available 
![image](https://user-images.githubusercontent.com/83023263/204757794-37c9dc81-261e-4e33-92ac-de8de78b71fe.png)

**Comment by cackazar** [comment]
Hello,
My apologies for the late reply. Here are the 2 screenshots of the issue
I was encountering when doing the codelab. In the image titled before the
image is moved to the background everything is the same in my studio as is
in the codelab, however when I move the image to the background the
hardcoded warnings for the textviews disappear. Also, in doing other
codelabs it seems that I was not supposed to necessarily pick anything on
the values screen when adding a drawable image which may have contributed
to this issue, once again I am sorry if my monkey brain caused any
confusion.

As a side note the other warning, in the after image is moved screenshot,
is an issue with the contrast ratio and studio telling me my textviews
might not be necessarily readable due to the color of the font, which is an
issue I was able to figure out on my own.

Respectfully,
Leon
