### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by EdilsonDiasAlves** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#157]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-unit-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-unit-tests#2

**In which task and step of the codelab can this issue be found?**
Step 8

**Describe the problem**
On this step, the text says: "Optional: For extra practice, modify the dice to be 4- or 5-sided without changing the assertion to see the test fail." But, with the assertion assuming a 6 sided dice, modifying the dice object to 4 or 5 sides will not display an error.
Instead, the suggestion should be: modifying the dice for a number above 6 or bellow zero. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by sam-ebe** [comment]
Juste closed my issue on this matter, there is a ton of duplicates of this one. Doesn't take much to correct this issue :) 
Up !
