### ISSUE TITLE
Android Basics issue: incorrect instructions in unit test tutorial

### ISSUE THREAD

**Issue by christate** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#162]
**URL of codelab**

https://developer.android.com/codelabs/android-basics-kotlin-write-unit-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-four%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-unit-tests#2

**In which task and step of the codelab can this issue be found?**

The '8. Optional' final suggested experiment/tweak.

**Describe the problem**

The final exercise reads:

> 8. Optional: For extra practice, modify the dice to be 4- or 5-sided without changing the assertion to see the test fail.

This is wrong!  Changing the `Dice` instance parameters to be 4- or 5- sided will never cause the example assertion to fail.  The assertion as developed at this point in the example test code is:

```
assertTrue("The value of rollResult was not between 1 and 6", rollResult in 1..6)
```

But rolling a 4- or 5-sided die will *also* always produce a result in 1..6, so the test will still always pass, contradicting the prompt in the exercise.

What needs to be changed is not the `Dice` instance, but the `assertTrue()` predicate that the result lies within the intended range, something like

```
assertTrue("The value of rollResult was not between 1 and 4", rollResult in 1..4)
```

...which will sometimes fail if `rollResult` is generated from a `Dice(6)` instance as developed through this exercise.

**Versions**

Any

**Comment by christate** [comment]
(Or, of course, the Dice instance could be given *more* than six sides, to start producing assertion failures with the predicate as given)

**Comment by ArrayBolt3** [comment]
I also noticed this while reading the codelab and thought it was probably wrong. There is a way to make a 5-sided die cause a test failure when checking for values between 1 and 6 inclusive, but it would require a much more in-depth change (i.e., generate 100 random rolls and if *none* of them were a 6, then fail the test). That's probably more than is needed for the codelab though.
