### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by y97856899** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#2

**In which task and step of the codelab can this issue be found?**
I do not know

**Describe the problem**
ParseError at [row,col]:[1,1]
Message: Content is not allowed in prolog.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Thank you @y97856899 for flagging this parse error. Can you provide a screenshot showing this error, and your activity_main.xml file? Thanks!
