### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by josuedlio** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#23]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
java.lang.OutOfMemoryError: Failed to allocate a 118054956 byte allocation with 1147400 free bytes and 94MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ashnohe** [comment]
Thank you @josuedlio for reporting this issue. Can you provide more details as to what step of the codelab you were on when you observed this out of memory error?
