### ISSUE TITLE
Android Basics issue: https://github.com/google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution/blob/master/androidparty.jpg IS NOT WORKING PLESE FIX IT

### ISSUE THREAD

**Issue by smart-kky** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#3]
[**URL](https://github.com/google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution/blob/master/androidparty.jpg) of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by 3lvis** [comment]
It's here https://github.com/google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution/blob/master/androidparty.png

The links here need to be updated: https://developer.android.com/codelabs/basic-android-kotlin-training-birthday-card-app-image?authuser=2&return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-three%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-birthday-card-app-image#1

**Comment by jtavva** [comment]
This issue should be fixed now, thank you!
