### ISSUE TITLE
Android Basics: Progress not saved

### ISSUE THREAD

**Issue by saclavij** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#4]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

many codelab have the problem

**Describe the problem**

When I completed the lab for example  Create a Birthday Card app it doesn't update the record (the progress yellow bar) and I am sure I logged in and I finished.

I have finished many activities but the progress bar is not updating.

I hope this will help you to improve the experience for everyone.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

![Snip20201027_19](https://user-images.githubusercontent.com/18658644/97306776-50a11780-1835-11eb-9808-adc81fbd8a1b.png)

**Comment by jkcoolmom** [comment]
Hello, are you still experiencing this issue?

**Comment by saclavij** [comment]
I have not tried in the last two weeks, I will check it again and I will let you know.

Thanks for asking

**Comment by jtavva** [comment]
@saclavij 
Thank you for reaching out to us.
This should be fixed now.
If you have any issues, please reopen this bug or file a new one.
