### ISSUE TITLE
Android Basics issue: Unit tests | 8. Optional | test will never fail

### ISSUE THREAD

**Issue by jzr-supove** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#62]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-unit-tests#2

**In which task and step of the codelab can this issue be found?**
3. Write your first unit test
└ 8. Optional: For extra practice, modify the dice to be 4- or 5-sided without changing the assertion to see the test fail.

**Describe the problem**
It says to run tests with 4 or 5 sided dice in orde to see the test fail. But this logic is wrong, and test will never fail since assertion is checking if the rolled number in range 1..6

**Solution**
It should say:

> For extra practice, modify the dice to be 7- or 8-sided without changing the assertion to see the test fail.

**Comment by moun3imy** [comment]
same as #76
