### ISSUE TITLE
Android Basics: birthday-card-app-image

### ISSUE THREAD

**Issue by Andy177-Apps** [google-developer-training/android-basics-kotlin-birthday-card-with-image-app-solution#8]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

The context is empty after importing into Android Studio

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 1.4.3
_API version of the emulator:_ 18

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Andy177-Apps 
Thank you for reaching out to us.
You should select `android-basics-kotlin-birthday-card-with-image-app-solution/HappyBirthday/`, when you import or open the project in the Android studio.
